services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_DATABASE_TYPE=sqlite
      - N8N_DATABASE_SQLITE_DATABASE=/home/node/.n8n/database.sqlite
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/home/node/.n8n
      - ./data/agendamentos.db:/home/node/agendamentos.db
    restart: unless-stopped
    networks:
      - n8n-network

  sqlite-init:
    image: alpine:latest
    container_name: sqlite-init
    volumes:
      - ./data:/data
      - ./init-db.sql:/init-db.sql
    command: >
      sh -c "
        apk add --no-cache sqlite &&
        sqlite3 /data/agendamentos.db < /init-db.sql &&
        chmod 666 /data/agendamentos.db
      "
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge 